### ISSUE TITLE
如何设定packageName

### ISSUE THREAD

**Issue by xlyasdasd** [YK-Unit/Flr#3]
执行flr run后的AssetResource的packageName都是空
AssetResource(
      "images/business_basketball_calendar_day.png",
      packageName: null);
实际需要根据子package设定对应的packageName，否则主工程执行加载图片报错

**Comment by YK-Unit** [comment]
感谢反馈。但需要进一步的信息以定位你说的问题。

- 此Repo已经迁移到新的Repo了： https://github.com/Fly-Mix/flr-cli
- 你现在使用的是上述新Repo的 flr-cli 版本吗？
- 如果是上述新Repo的 flr-cli 版本，麻烦提供一下你所使用的版本号？
- 你也可以直接升级到 flr-cli 最新版本，看是否能解决你当前的问题
- 如果 flr-cli 最新版本不能解决你的问题，希望你能提供一下demo过来帮忙改善，谢谢

**Comment by xlyasdasd** [comment]
> 感谢反馈。但需要进一步的信息以定位你说的问题。
> 
> * 此Repo已经迁移到新的Repo了： https://github.com/Fly-Mix/flr-cli
> * 你现在使用的是上述新Repo的 flr-cli 版本吗？
> * 如果是上述新Repo的 flr-cli 版本，麻烦提供一下你所使用的版本号？
> * 你也可以直接升级到 flr-cli 最新版本，看是否能解决你当前的问题
> * 如果 flr-cli 最新版本不能解决你的问题，希望你能提供一下demo过来帮忙改善，谢谢

感谢回复，写了个复现Demo，App工程依赖Module项目会出现
[flutter_app_test.zip](https://github.com/YK-Unit/Flr/files/5167909/flutter_app_test.zip)
core_version: 3.1.0

**Comment by YK-Unit** [comment]
好的。感谢你的demo。

**Comment by YK-Unit** [comment]
@xlyasdasd 有些上下文我们需要对齐一下。

按照Flutter官方的设定，Flutter共有四种工程类型，然后不同工程类型应用不同业务场景，具体如下：
- app：Flutter App工程，用于开发纯Flutter的App
- module：Flutter Component工程，用于开发Flutter组件以嵌入iOS和Android原生工程
- package：General Dart Package工程，用于开发一个供应用层开发者使用的包
- plugin：Plugin Package工程（属于特殊的Dart Package工程），用于开发一个调用特定平台API的包

针对这样的设定，Flr在对资源做处理时，只对工程类型为`package`和`plugin`的工程的资源指定`packageName`，即为其生成代码：
``` dart
final test_png_variant_1 = const AssetResource(
      "assets/images/test_asset_variants/test_png_variant_1.png",
      packageName: R.package);
```

目前你的主工程师需要依赖一个子package，这时应当遵守Flutter官方的设定，去建立一个`package`类型的子工程，而不是一个`module`类型的子工程。

如果你需要研究不同工程类型的Demo，可使用我们提供的以下Demo：

- [flutter_hello_app](https://github.com/Fly-Mix/flutter_hello_app)
- [flutter_hello_module](https://github.com/Fly-Mix/flutter_hello_module)
- [flutter_hello_package](https://github.com/Fly-Mix/flutter_hello_package)
- [flutter_hello_plugin](https://github.com/Fly-Mix/flutter_hello_plugin)

**Comment by xlyasdasd** [comment]
> 以下

好的，谢谢
